In [3]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

In [2]:
# Decomposing an Array into its SVD.

A = array([[1,2], [3,4], [5,6]])
print(A)

# decomposing a MATRIX into its constituent elements
U, s, VT = svd(A)

# 'U' is an orthagonal matrix. The columns of 'U' matrix are AKA 'Left Singular Matrix' of the original matrix.
print(U)

# 's' is a diagonal matrix, and is AKA singular value of the original matrix.
print(s)

# 'VT' is an orthagonal matrix. The columns of 'VT' matrix are AKA 'Right Singular Matrix' of the original matrix.
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [6]:
# Reconstructing the original matrix

#Sigma = zeros((A.shape[0], A.shape[1]))
#Sigma[: A.shape[1], :A.shape[1]] = diag(s)

Sigma = diag(s)
B = U.dot(Sigma.dot(VT))

print(B)

ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)